name: Build
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install @parcel/transformer-sass
        run: npm i @parcel/transformer-sass

      - name: Build
        run: npx parcel build src/index.html --dist-dir build --public-url ./

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
          cname: triangulation.presentation.masahiro.dev
